### ISSUE TITLE
Failing to play on my own server.

### ISSUE THREAD

**Issue by JollyTeh** [thehobojoe/Progress#26]
Hi there. I've been wanting to make my own server to play with a friend for this modpack but it seems that everytime I attempt to enter the server I get this failure:

Registry remapping failed: Received ID map for minecraft:enchantment contains IDs unknown to the receiver!
 - spectrum:disarming      - spectrum:improved_critical.
 
 I had this issue running the server a few updates ago but somehow fixed it and now it came back. I did however attempt to reload the nether by deleting the file corresponding to it in the world folder if that has any correlation.

**Comment by thehobojoe** [comment]
Make sure that the server and the client both have the same Spectrum version, and the same spectrum config
